
#
# UI to download sample datasets
# 


library(shiny)

shinyUI(fluidPage(
    titlePanel('Compilation of KPI report'),
    sidebarLayout(
        # 1st Sidebar
        sidebarPanel(
            # adding the new div tag to the sidebar            
            tags$div(class="header", checked=NA,
                h4("1. Download the sample data of A&E waiting time"), br(),
                tags$a(href="./source/Jan20/kpi.1_AE_WT_2020-01.xlsx", "January 2020"), br(),
                tags$a(href="./source/Jan21/kpi.1_AE_WT_2021-01.xlsx", "January 2021"), br(), br(),
                # view sample data
                selectInput("dataset", "View the sample dataset:", 
                            choices = c("2020-Jan", "2021-Jan")),
                selectInput("triage", "Select triage:",
                            choices = c("Tri 1", "Tri 2", "Tri 3", "Tri 4", "Tri 5")),
                
                # Upload data
                h4("2. Upload the system generated data required for each KPI item"), br(),
                tags$strong("kpi.1 A&E Waiting Time"), br(), br(),
                fileInput("kpi.1_ty", label = "kpi.1 This Year", multiple = FALSE,
                          accept = c("application/vnd.ms-excel",
                                     "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                                     ".xls",
                                     ".xlsx")),
                fileInput("kpi.1_ly", label = "kpi.1 Last Year", multiple = FALSE,
                          accept = c("application/vnd.ms-excel",
                                     "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                                     ".xls",
                                     ".xlsx")),
                
                tags$strong("kpi.2 SOP waiting time"), br(),
                tags$p("[Demo of concept only, for a full fledged app many source data will be uploaded...]"),
                br(), br(),
                
                # Download compiled data
                h4("3. Download the compiled KPI report"), br(),
                downloadButton('downloadData', 'Download')
                
            )
        ),
        
        mainPanel(
            tabsetPanel(
                tabPanel("Readme", h4("Introduction"),
                         tags$p("This app will compile a sample Key Performance Indicator report from multiple
                                sources of data in the form of Excel files generated from different corporate 
                                information systems. The data can be visualised, while a compiled KPI report 
                                in the form of an Excel file can be downloaded."),
                         tags$p("In this demonstration we are attempting to compile a KPI report for the 
                                management of a group of hospitals. The only item reported is the waiting time 
                                for the Accident & Emergency room for different triage categories. The source 
                                data is composed of 2 parts:"),
                         tags$ol(type = "A",
                             tags$li(em("the percentage of A&E cases seen within the pleged waiting time in the 
                                       for the past 12 months reporting period")),
                             tags$li(em("the percentage for the same reporting period of last year"))
                         ),
                         tags$p("The report compares the percentages between this year and last year. In 
                                addition, the performance of the hospitals within the group are compared with 
                                the overall conuntry-wide performace."),
                         tags$p("As a bit of technical note, the Excel spread sheets is generated by filling the data 
                                to cells in a prepared template."),
                         
                         tags$hr(),
                         
                         h4("How to use this app?"),
                         tags$p("To use this app, follow the 3 steps from the sidebar:"),
                         
                         tags$strong("Step 1: Download the sample data of A&E waiting time"), br(),
                         tags$p("In real life operation, this step is not done with this app. In a large 
                                corporation the data required to compile each KPI may be awailable from 
                                several data sources. This may include various information or even manual 
                                reporting."),
                         tags$p("For the sample data, let's assume that right now it is ", tags$strong("January 2021, "),
                                "and hence last year would be ", tags$strong("January 2020."), "The data can 
                                be visualised in the ", tags$em("Sample Dataset"), "tab."),
                         
                         tags$strong("Step 2: Upload the system generated data required for each KPI item"),
                         
                         tags$strong("Step 3: Download the compiled KPI report"),
                         tags$p("Just click", tags$strong("Download"), "and", tags$em("voilà!"))
                         ),
                
                tabPanel("Sample Dataset", h4(textOutput("dsname")), plotOutput('samplePlot'), tableOutput('table')),
                
                tabPanel("Uploaded Dataset",
                         h4("This year's data"),
                         tableOutput('tyTable'), br(),
                         h4("Last year's data"),
                         tableOutput('lyTable')),
                
                tabPanel("Plots", h4("kpi.1 A&E Waiting Time"), plotOutput('kpi.1Plot'))
            )
        )
        
    )
))